name: Build and Release

on:
  workflow_dispatch:
    inputs:
      target_branch:
        description: "Switch branch"
        required: true
        default: "wip"

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: linux-glibc
          - os: ubuntu-latest
            target: linux-musl
          - os: windows-latest
            target: win64

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.target_branch }}
      
      - name: Get version
        id: vars
        shell: bash
        run: |
          VERSION=$(grep "VERSION" ./xorcrypt.h | cut -d ' ' -f 3 | tr -d ' "' || echo V)
          echo "ver_str=$VERSION" >> $GITHUB_OUTPUT
      
      - name: Build on Linux with glibc
        if: matrix.target == 'linux-glibc'
        run: |
          sudo apt update
          sudo apt install -y build-essential libssl-dev
          make distclean dist disttest

      - name: Build on Linux with musl inside Alpine
        if: matrix.target == 'linux-musl'
        run: |
          docker run --rm -v ${{ github.workspace }}:/src -w /src alpine:latest \
            sh -c "
              apk add --no-cache build-base openssl-dev &&
              make distclean dist disttest
            "
      
      - name: Build on Windows
        if: matrix.target == 'win64'
        shell: bash
        run: make distclean dist disttest

      - name: Archiving for Linux
        if: matrix.target == 'linux-glibc' || matrix.target == 'linux-musl'
        run: |
          chmod +x ./xorcrypt ./xorcrypt-avx2
          tar -cvzf xorcrypt-${{ steps.vars.outputs.ver_str }}-${{ matrix.target }}.tar.gz \
          xorcrypt \
          xorcrypt-avx2 \
          README.md \
          LICENSE
      
      - name: Archiving for Windows
        if: matrix.target == 'win64'
        shell: bash
        run: |
          zip xorcrypt-${{ steps.vars.outputs.ver_str }}-${{ matrix.target }}.zip \
          xorcrypt.exe \
          xorcrypt-avx2.exe \
          README.md \
          LICENSE

      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.target }}-archive
          path: |
            *.tar.gz
            *.zip
  
  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.target_branch }}
      
      - name: Get version
        id: vars
        shell: bash
        run: |
          VERSION=$(grep "VERSION" ./xorcrypt.h | cut -d ' ' -f 3 | tr -d ' "' || echo V)
          echo "ver_str=$VERSION" >> $GITHUB_OUTPUT

      - name: Fetch artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./dist
      
      - name: Create draft-release
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh release create ${{ steps.vars.outputs.ver_str }} ./dist/* --draft --generate-notes
