name: Build and Upload binary

on:
  workflow_dispatch:
    inputs:
      target_branch:
        description: "Switch branch"
        required: true
        default: "wip"

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: glibc
          - os: ubuntu-latest
            target: musl
          - os: windows-latest
            target: windows

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.target_branch }}
      
      - name: Show branch
        run: echo "Switch ${{ github.event.inputs.target_branch }}"

      - name: Set version
        id: vars
        shell: bash
        run: |
          VERSION=$(grep "VERSION" ./xorcrypt.h | cut -d ' ' -f 3 | tr -d ' ' || echo V)
          echo "ver_str=$VERSION" >> $GITHUB_OUTPUT
      
      - name: Build on Linux with glibc
        if: matrix.target == 'glibc'
        run: |
          sudo apt update
          sudo apt install -y build-essential libssl-dev
          make distclean dist disttest

      - name: Build on Linux with musl inside Alpine
        if: matrix.target == 'musl'
        run: |
          docker run --rm -v ${{ github.workspace }}:/src -w /src alpine:latest \
            sh -c "
              apk add --no-cache build-base openssl-dev &&
              make distclean dist disttest
            "
      
      - name: Build on Windows
        if: matrix.target == 'windows'
        shell: bash
        run: make distclean dist disttest

      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: xorcrypt-${{ steps.vars.outputs.ver_str }}-${{ matrix.target }}
          path: |
            ./xorcrypt
            ./xorcrypt-avx2
            ./xorcrypt.exe
            ./xorcrypt-avx2.exe
            ./README.md
            ./LICENSE
