name: Build and Release

on:
  workflow_dispatch:
    inputs:
      build_linux_glibc:
        description: "Build for x86-64 Linux-glibc"
        type: boolean
        default: true
      build_linux_musl:
        description: "Build for x86-64 Linux-musl"
        type: boolean
        default: true
      build_windows_ucrt:
        description: "Build for x86-64 Windows-ucrt"
        type: boolean
        default: true
      target_branch:
        description: "Switch branch to"
        required: true
        default: "main"

permissions:
  contents: write

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-linux-glibc
          - os: ubuntu-latest
            target: x86_64-linux-musl
          - os: windows-latest
            target: x86_64-windows-ucrt

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.target_branch }}
      
      - name: Get version
        id: vars
        shell: bash
        run: |
          VERSION=$(grep "VERSION" ./xorcrypt.h | cut -d ' ' -f 3 | tr -d ' "' || echo V)
          echo "ver_str=$VERSION" >> $GITHUB_OUTPUT
      
      - name: Build on Linux with glibc
        if: |
          github.event.inputs.build_linux_glibc == 'true' &&
          matrix.target == 'x86_64-linux-glibc'
        run: |
          sudo apt update
          sudo apt install -y build-essential libssl-dev
          make distclean dist disttest
          chmod +x ./xorcrypt ./xorcrypt-avx2
          tar -cvzf xorcrypt-${{ steps.vars.outputs.ver_str }}-${{ matrix.target }}.tar.gz \
          xorcrypt \
          xorcrypt-avx2 \
          README.md \
          LICENSE

      - name: Build on Linux with musl inside Alpine
        if: |
          github.event.inputs.build_linux_musl == 'true' &&
          matrix.target == 'x86_64-linux-musl'
        run: |
          docker run --rm -v ${{ github.workspace }}:/src -w /src alpine \
            sh -c "
              apk add --no-cache build-base openssl-dev &&
              make distclean dist disttest &&
              chmod +x ./xorcrypt ./xorcrypt-avx2 &&
              tar -cvzf xorcrypt-${{ steps.vars.outputs.ver_str }}-${{ matrix.target }}.tar.gz \
              xorcrypt \
              xorcrypt-avx2 \
              README.md \
              LICENSE
            "
            
      - name: Build on Windows
        if: |
          github.event.inputs.build_windows_ucrt == 'true' &&
          matrix.target == 'x86_64-windows-ucrt'
        shell: bash
        run: make distclean dist disttest

      #- name: Build on Windows with w64devkit
      #  if: |
      #    github.event.inputs.build_windows == 'true' &&
      #    matrix.target == 'win64'
      #  shell: bash
      #  run: |
      #    mkdir _tmp
      #    curl -L https://github.com/skeeto/w64devkit/releases/download/v2.7.0/w64devkit-x64-2.7.0.7z.exe -o _tmp/w64d_setup.exe
      #    ./_tmp/w64d_setup.exe -y -o_tmp
      #    export PATH="${GITHUB_WORKSPACE}/_tmp/w64devkit/bin:${PATH}"
      #    make distclean dist disttest

      - name: Archive for Windows
        if: |
          github.event.inputs.build_windows_ucrt == 'true' &&
          matrix.target == 'x86_64-windows-ucrt'
        shell: pwsh
        run: |
          Compress-Archive -DestinationPath xorcrypt-${{ steps.vars.outputs.ver_str }}-${{ matrix.target }}.zip -Path `
          xorcrypt.exe,
          xorcrypt-avx2.exe,
          README.md,
          LICENSE

      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.target }}-archive
          path: |
            *.tar.gz
            *.zip
  
  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.target_branch }}
      
      - name: Get version
        id: vars
        shell: bash
        run: |
          VERSION=$(grep "VERSION" ./xorcrypt.h | cut -d ' ' -f 3 | tr -d ' "' || echo V)
          echo "ver_str=$VERSION" >> $GITHUB_OUTPUT

      - name: Fetch artifacts
        uses: actions/download-artifact@v4
        with:
          merge-multiple: true
      
      - name: Create draft-release
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          files=$(ls *.tar.gz *.zip 2>/dev/null || true)
          if [ -n "$files" ]
          then
            gh release create ${{ steps.vars.outputs.ver_str }} ${files} --draft --generate-notes
          fi
